# Create xrizer symlink in /opt for steam to easier find it
# Type  Path            Mode UID  GID  Age  Argument
R!      /opt/xrizer     -    -    -    -    -
C!      /opt/xrizer     -    -    -    -    /usr/lib/xrizer
Z       /opt/xrizer     -    -    -    -    -
