name: Build Containers

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  #push:
  #  branches:
   #   - main
   # paths-ignore:
   #   - '**/README.md'

jobs:
  build-kde-nvidia-image:
    uses: ./.github/workflows/build-kde.yml
    secrets: inherit
  build-gnome-nvidia-image:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  build-kde-image:
    uses: ./.github/workflows/build-kde_mesa.yml
    secrets: inherit
  build-gnome-image:
    uses: ./.github/workflows/build_mesa.yml
    secrets: inherit
